### ISSUE TITLE
flex

### ISSUE THREAD

**Issue by zdolny** [AgaMiasek/Trello#1]
- [x] przypilnuj wciec w js, pamietaj, ze w sublime jest opcja:
 view -> indentation -> convert indentation to spaces/tabs
u mnie mniejsze wciecia powinny byc w liniach: 2, 42, 43, 101-103, a wieksze w liniach: 68-74
- [x] taka sytuacja: https://scr.hu/mZy9l4 Jak uzywasz floatow, to uzyj clearfixa na rodzicu, wtedy zamien tez wysokosc kontenera na min-width i dodaj padding od dolu

Ogolnie tablica wyglada super, ale jest jeden minus ukladania kolumn przez `float: left`. Przy szczegolnym przypadku, elementy plyna do lewej i zatrzymuja sie na tym, co wystaje: https://scr.hu/jeXdjA. Jako zadanie nieobowiazkowe, sprobuj ulozyc te kolumny za pomoca flexboxa.

**Comment by michal-bootcamp** [comment]
jest ok, dorzucilem pare poprawek: wciecia w js, likwidacje clearfixa w html i css i troche poprawilem flexa - jak bedziesz miala kiedys chwile to zainteresuj sie flexem bardziej, to super sprawa :)
Zmiany tutaj: https://github.com/AgaMiasek/Trello/commit/6fc9a37f54ca68acc16f69c1a430e7aa49700f1f
